# Generated by Django 2.2.1 on 2019-05-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='title')),
                ('link', models.URLField(verbose_name='link')),
                ('description', models.TextField(verbose_name='description')),
                ('image_link', models.URLField(verbose_name='image_link')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=254, verbose_name='store_name')),
            ],
        ),
    ]
