# Generated by Django 2.2.1 on 2019-05-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.URLField(max_length=254, verbose_name='image_link'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(max_length=254, verbose_name='link'),
        ),
    ]
