# Generated by Django 2.2.1 on 2019-05-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20190505_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.URLField(blank=True, max_length=254, null=True, verbose_name='image_link'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, max_length=254, null=True, verbose_name='link'),
        ),
    ]
