# Generated by Django 2.2.1 on 2019-05-05 21:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20190505_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.Store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='image_link'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='link'),
        ),
    ]
